### ISSUE TITLE
Java toolchains support

### ISSUE THREAD

**Issue by Vampire** [iherasymenko/jlink-gradle-plugin#1]
Please support Java toolchains.
There are two points about it.
1. being able to configure a toolchain from which the jlink tool is used from
2. being able to configure a toolchain (additionally to, not instead) as jdk to take the jmods from

If you run Gradle with Java 11 and try to build a runtime for Java 17, the Java 11 jlink tool cannot read the jmods of the Java 17 JDK.

**Comment by iherasymenko** [comment]
Hi @Vampire. I didn't expect anybody besides me would use this plugin :-)

No promises on the timeline, but I'll look into this.

P.S. thank you for all your support that you provide on the Gradle Slack.

**Comment by Vampire** [comment]
Well, it was the first result on the portal. But actually after writing this I tried the second and that plugin(s) is yours on steroids. I can just recommend you to use it too and don't worry to make this change here. :-) It is the badass jlink and runtime plugins, depending on whether you build a modular or classpath app. :-)

**Comment by iherasymenko** [comment]
Hi @Vampire . I know it's been a while but I just want to let you know that I just implemented the functionality you requested ;-)

Please refer to this test case for more details. https://github.com/iherasymenko/jlink-gradle-plugin/blob/a4880cfeeb45fc6c0bec0f92f43325508d9b197b/src/test/java/com/github/iherasymenko/jlink/test/CrossTargetJdkImageFunctionalTest.java#L15-L85

**Comment by Vampire** [comment]
Thanks.
But tbh, I don't see how that test demonstrates the request, especially point 2.

**Comment by iherasymenko** [comment]
Sorry @Vampire. It is, indeed, does not directly address your use cases, although it has almost all the building blocks in it. Let me try to elaborate here.

Let's say we have the setup as follows.

Gradle is running on JDK 11. Your project is configured to use the JDK 17 toolchain, i.e 17 is used for compilation, testing, etc. 

`build.gradle`

```
plugins {
    id 'application'
    id 'com.github.iherasymenko.jlink' version '0.5'
}

...

java {
 toolchain {
  languageVersion = JavaLanguageVersion.of(17)
  vendor = JvmVendorSpec.AZUL
 }
}
```

You want to use jlink from JDK 18 (use case 1) for building your images. You should be able to achieve this by configuring the `JlinkImageTask`  task(s).
```
tasks.withType(com.github.iherasymenko.jlink.JlinkImageTask).configureEach { task ->
	task.javaLauncher = javaToolchains.launcherFor {
		languageVersion = JavaLanguageVersion.of(18)
		vendor = JvmVendorSpec.AZUL
	}
}
```

I will probably add this to the DSL in the future. For now, configuring the task(s) should do the trick. The `image` task will now be powered by `jlink` from the JDK 18.

For the use case (2) configuring "jdk to take the jmods from", it gets a little bit harder, as the JVM Toolchain API does not allow requesting a specific JDK version of the specific vendor for the specific platform. All we can do is to request a major version (with vendor) of a JDK for the _current_ platform. This is not great, especially if we want to cross build images for several platforms.

However, this plugin overcomes this problem by downloading JDKs from a CDN (repository) and using them as the source of "jmods". This way, we can be in full control of the minor version, platform, flavor, etc.

I will use Azul Zulu CDN in this example. Let's configure the repository first.

`settings.gradle`
```
dependencyResolutionManagement {
    repositories {
        ivy {
            url = uri("https://cdn.azul.com/zulu/bin/")
            patternLayout {
                artifact "[artifact].[ext]"
            }
            metadataSources {
                artifact()
            }
            content {
                includeGroup("com.azul.cdn")
            }
        }
```

And now when the JDK repository is defined, we can configure the additional image builds via the DSL.

`build.gradle`
```
jlinkImages {
 linuxX64 {
  group = 'com.azul.cdn'
  jdkArchive = 'zulu18.30.11-ca-jdk18.0.1-linux_x64.zip'
 }
 windowsX64 {
  group = 'com.azul.cdn'
  jdkArchive = 'zulu18.30.11-ca-jdk18.0.1-win_x64.zip'
 }
 macOsXAarch64 {
  group = 'com.azul.cdn'
  jdkArchive = 'zulu18.30.11-ca-jdk18.0.1-macosx_aarch64.tar.gz'
 }
}
```

This configuration will add the three tasks (`imageLinuxX64`, `imageWindowsX64`, and `imageMacOsXAarch64`) to the build. 

If you want to be more granular, for instance, build one image with "jmods" from JDK 18, and the other image with "jmods" from JDK 19, you can achieve this by configuring each `image*` task individually to use a specific toolchain .

```
jlinkImages {

...

 linuxX64Jdk19 {
  group = 'com.azul.cdn'
  jdkArchive = 'zulu19.32.13-ca-jdk19.0.2-linux_x64.tar.gz'
 }
}

tasks.named('imageLinuxX64Jdk19', com.github.iherasymenko.jlink.JlinkImageTask) { task ->
	task.javaLauncher = javaToolchains.launcherFor {
		languageVersion = JavaLanguageVersion.of(19)
		vendor = JvmVendorSpec.AZUL
	}
}
```

Hope this helps!

**Comment by Vampire** [comment]
Thanks for the explanation :-)
